link-shortener:
    short-link-length: 15
logging:
    web-request-body-masked-props:
        - $.body.active
        - $.body.page.size
        - $.id
    execution-log-enabled: true
    web-request:
        enabled: true
        body:
            enabled: true


server:
    servlet:
        context-path: /link-shortener
